#!/bin/sh

# system dirs
[ -d /proc ]	|| mkdir			/proc
[ -d /sys ]		|| mkdir			/sys
[ -d /dev ]		|| mkdir -m 0755	/dev
[ -d /dev/pts ]	|| mkdir			/dev/pts

mount -t proc 			proc	/proc		-o nodev,noexec,nosuid
mount -t sysfs			sysfs	/sys		-o nodev,noexec,nosuid
mount -t devtmpfs		udev	/dev
mount -t devpts			devpts	/dev/pts	-o noexec,nosuid,gid=5,mode=0620

exec setsid cttyhack /bin/sh

